import type { Metadata } from "next";
import "./globals.css";
import NavigatorComponent from "./components/navigator/navigator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className ="headerContainer">
            <NavigatorComponent></NavigatorComponent>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
